####   CONFIGURATION   ####
DATA :
  DATA_ROOT  : data
  IMAGE_PATH  : sample
  TEST_FOLDER : sample
  TRAIN_PATH : Train.txt
  VALID_PATH : Valid.txt
  TEST_PATH  : Test.txt
  VALID_RATE : 0.2

TRAIN :
  NUM_WORKER    : 4
  SAVE_PERIOD   : 20

TEST :
  BATCH_SIZE    : 64
  NUM_WORKER    : 4
  SAMPLE_PATH   : sample_submission.csv