####   CONFIGURATION   ####
DATA :
  DATA_ROOT  : data
  IMAGE_PATH  : sample
  TRAIN_PATH : Train.txt
  VALID_PATH : Valid.txt
  TEST_PATH  : Test.txt
  VALID_RATE : 0.2

TRAIN :
  MAX_LEN       : 144 ## 24*6
  NUM_WORKER    : 4

TEST :
  BATCH_SIZE    : 64
  NUM_WORKER    : 4
  SUBMIT_PATH   : output/test0/submission.csv