####   CONFIGURATION   ####
TRAIN :
  BATCH_SIZE    : 2
  CLASS_N       : 6 #111
  LEARNING_RATE : 0.0001
  DROPOUT_RATE  : 0.2
  EPOCHS        : 30
  VISION_PRETRAIN : True
  SAVE_PATH     : output/dense0