####   CONFIGURATION   ####
TRAIN :
  BATCH_SIZE    : 4
  CLASS_N       : 25
  LEARNING_RATE : 0.0001
  EMBEDDING_DIM : 512
  DROPOUT_RATE  : 0.1
  EPOCHS        : 30
  SAVE_PATH     : output/test0

  ### CSV ###
  USE_CSV       : True
  MAX_LEN       : 294
  NUM_FEATURES  : 13
  RESNET_DEPTH  : 2
  CSV_DROP_RATE : 0.3

  ### IMAGE ###
  USE_SPOT    : True
  USE_AUG     : True
  IMAGE_SIZE  : 256
  IMAGE_WIDTH : 368
  IMAGE_HEIGHT: 256
  PATCHES     : 16
  D_MODEL     : 512
  N_HEAD      : 8
  FF_DIM      : 2048
  DROP_OUT    : 0.1
  ENCODER :
    NUM_LAYER : 6
  DECODER :
    NUM_LAYER : 6